highlighter: "rouge"
# - markdown: "kramdown"

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post

plugins:
  - jekyll-sitemap

title: "xtof"
tagline: ""
description: "Follow <a href=\"https://micro.blog/xtof\">@xtof on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/xtof\">@xtof on Micro.blog</a>."
baseurl: ""
url: "https://microblog.ducamp.me"
markdown: "kramdown"
username: "xtof"
microblog_user: "xtof"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "xtof"
name: "xtof"
gravatar_hash: "3c91a6d10d3cf2a57090ffa9176d0f32"
avatar: "https://micro.blog/xtof/avatar.jpg"
full_name: "xtof"
bio: ""
twitter_username: "xtof_party"
github_username: "ChristopheDucamp"
instagram_username: "xtof_fr"
paginate: 20
paginate_path: "/page/:num/"
timezone: "Poland"
site_id: "3650"
gems: ["jekyll-paginate"]
itunes_description: "Apprenti marin sur la route de l'indieweb. 
Première transat fin octobre. 
30 jours pour apprendre à déposer quelques lignes de journal de bord à l'attention de mon Papa via une liaison iridium."
itunes_category: "Society & Culture"
itunes_subcategory: "Personal Journals"
itunes_author: "Christophe Ducamp"
itunes_email: ""
podcast: false