# Dependencies
# - markdown:         redcarpet
highlighter:      rouge

# Permalinks
# - permalink:        pretty
# - relative_permalinks: true

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

title: "xtof"
tagline: ""
description: "Follow <a href=\"https://micro.blog/xtof\">@xtof on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/xtof\">@xtof on Micro.blog</a>."
baseurl: ""
url: "https://microblog.ducamp.me"
markdown: "kramdown"
username: "xtof"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "xtof"
name: "xtof"
gravatar_hash: "3c91a6d10d3cf2a57090ffa9176d0f32"
avatar: "https://micro.blog/xtof/avatar.jpg"
full_name: "xtof"
bio: ""
twitter_username: "xtof_party"
github_username: "ChristopheDucamp"
instagram_username: "xtof_fr"
paginate: 20
paginate_path: "/page/:num/"
timezone: "Poland"
site_id: "3650"
gems: ["jekyll-paginate"]